apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-list
  template:
    metadata:
      labels:
        app: todo-list
    spec:
      containers:
      - name: todo-list
        image: babydevcode/todo-list:latest
        ports:
        - containerPort: 80
        resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
