name: CI

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
    
      - name: Set environment variables
        run: echo "SQLITE_DB_LOCATION=$GITHUB_WORKSPACE/todos" >> $GITHUB_ENV
  
      - name: Create todos directory
        run: mkdir -p $GITHUB_WORKSPACE/todos

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test